# Generated by Django 5.2.6 on 2025-11-04 18:44

import utilisateurs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_profil',
            field=models.ImageField(blank=True, default='images/profiles/default.jpg', upload_to='images/profiles/%Y/%m/%d/', validators=[utilisateurs.models.validate_file_extension, utilisateurs.models.validate_file_size], verbose_name='image_de_profil'),
        ),
    ]
