# Generated by Django 5.2.5 on 2025-11-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_alter_user_password'),
        ('utilisateurs', '0002_userprofile_first_login'),
    ]

    operations = [
    ]
