# Generated by Django 5.2.5 on 2025-10-01 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_alter_user_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_abonement', models.CharField(choices=[('mensuel', 'Mensuel'), ('annuel', 'Annuel'), ('premium', 'Premium')], max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('card_number', models.CharField(max_length=16)),
                ('expiration_date', models.DateField()),
                ('cvv', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'abonement',
                'verbose_name_plural': 'abonements',
                'constraints': [models.UniqueConstraint(fields=('user', 'type_abonement'), name='unique_user_abonement')],
            },
        ),
    ]
