# Generated by Django 5.2.5 on 2025-10-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_alter_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_profil',
            field=models.ImageField(blank=True, default='profils/default.png', null=True, upload_to='profils/'),
        ),
    ]
