# Generated by Django 5.2.5 on 2025-10-07 13:39

import utilisateurs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_abonement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_profil',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/', validators=[utilisateurs.models.validate_file_extension, utilisateurs.models.validate_file_size], verbose_name='image_de_profil'),
        ),
    ]
